default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

stages:
  - build
  - test
  - security

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SAST_ENABLED: "true"
  SECRET_DETECTION_ENABLED: "true"
  GARMIN_USERNAME: test_user
  GARMIN_PASSWORD: test_user
  DB_HOST: postgres
  DB_PORT: 54322
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: garmin_heart_rate_test
  NODE_ENV: test
  REACT_APP_API_PORT: 3001
  REACT_APP_API_URL: http://localhost:${REACT_APP_API_PORT}

# Override security jobs to run only for main branch or merge requests
semgrep-sast:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID

secret_detection:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID

build:
  stage: build
  image: docker:latest
  script:
    - docker-compose build
  artifacts:
    expire_in: 1 hour
    # reports:
    #   dotenv: .env.test
  only:
    - main
    - merge_requests

test:
  stage: test
  image: docker:latest
  script:
    # - npm install
    # - cd backend && npm install
    # - cd frontend && npm install
    - mkdir -p backend/coverage frontend/coverage coverage
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml run frontend
    - docker-compose -f docker-compose.test.yml wait backend
    - apk add --no-cache nodejs npm lcov python3 py3-pip
    - python3 -m venv /tmp/venv
    - source /tmp/venv/bin/activate && pip install lcov_cobertura
    - lcov -o coverage/combined-lcov.info -a backend/coverage/lcov.info -a frontend/coverage/lcov.info
    - genhtml coverage/combined-lcov.info --output-directory coverage/html --ignore-errors source,unmapped --synthesize-missing
    - source /tmp/venv/bin/activate && lcov_cobertura coverage/combined-lcov.info --output coverage/cobertura-coverage.xml
  after_script:
    - docker-compose -f docker-compose.test.yml down -v
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit: 
        - backend/junit.xml
        - frontend/junit.xml
    paths:
      - backend/coverage/
      - frontend/coverage/
      - coverage/
      - backend/junit.xml
      - frontend/junit.xml
    expire_in: 1 week
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  only:
    - main
    - merge_requests



